In [1]:
import numpy as np
import pandas as pd

In [2]:
colunas_filmes = ['star_rating', 'title', 'content_rating', 'genre', 'duration', 'actors_list']

file ="c:\\Users\\dan\\Documents\\Curso Data Science\\Datasets\\movies.csv"
filmes = pd.read_csv(file, header=0, names=colunas_filmes)
filmes.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [4]:
type(filmes)

pandas.core.frame.DataFrame

In [7]:
filmes.title.sort_values().head(120)

542         (500) Days of Summer
5                   12 Angry Men
201             12 Years a Slave
698                    127 Hours
110        2001: A Space Odyssey
                 ...
651                Blood Simple.
725                         Blow
673                      Blow-Up
456    Blue Is the Warmest Color
972               Blue Valentine
Name: title, Length: 120, dtype: object

In [8]:
A = filmes.title.sort_values()
type(A)

pandas.core.series.Series

In [9]:
A.tail()

955    Zero Dark Thirty
677              Zodiac
615          Zombieland
526                Zulu
864               [Rec]
Name: title, dtype: object

In [10]:
filmes.title.sort_values(ascending=False).head(10)

864                 [Rec]
526                  Zulu
615            Zombieland
677                Zodiac
955      Zero Dark Thirty
535                 Zelig
280    Young Frankenstein
96                Yojimbo
235               Yip Man
403            Ying xiong
Name: title, dtype: object

In [15]:
filmes.sort_values('title').head()

,star_rating,title,content_rating,genre,duration,actors_list
542,7.8,(500) Days of Summer,PG-13,Comedy,95,"[u'Zooey Deschanel', u'Joseph Gordon-Levitt', ..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
201,8.1,12 Years a Slave,R,Biography,134,"[u'Chiwetel Ejiofor', u'Michael Kenneth Willia..."
698,7.6,127 Hours,R,Adventure,94,"[u'James Franco', u'Amber Tamblyn', u'Kate Mara']"
110,8.3,2001: A Space Odyssey,G,Mystery,160,"[u'Keir Dullea', u'Gary Lockwood', u'William S..."

In [16]:
filmes.sort_values('title', ascending=False).head()

,star_rating,title,content_rating,genre,duration,actors_list
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."
526,7.8,Zulu,UNRATED,Drama,138,"[u'Stanley Baker', u'Jack Hawkins', u'Ulla Jac..."
615,7.7,Zombieland,R,Comedy,88,"[u'Jesse Eisenberg', u'Emma Stone', u'Woody Ha..."
677,7.7,Zodiac,R,Crime,157,"[u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."

In [18]:
filmes.sort_values(['genre', 'duration']).head(20)

,star_rating,title,content_rating,genre,duration,actors_list
533,7.8,Run Lola Run,R,Action,80,"[u'Franka Potente', u'Moritz Bleibtreu', u'Her..."
633,7.7,The Warriors,R,Action,92,"[u'Michael Beck', u'James Remar', u'Dorsey Wri..."
455,7.9,Taken,PG-13,Action,93,"[u'Liam Neeson', u'Maggie Grace', u'Famke Jans..."
685,7.7,First Blood,R,Action,93,"[u'Sylvester Stallone', u'Brian Dennehy', u'Ri..."
744,7.6,Mad Max 2: The Road Warrior,R,Action,94,"[u'Mel Gibson', u'Bruce Spence', u'Michael Pre..."
619,7.7,Forbidden Planet,PASSED,Action,98,"[u'Walter Pidgeon', u'Anne Francis', u'Leslie ..."
276,8.1,A Fistful of Dollars,R,Action,99,"[u'Clint Eastwood', u'Gian Maria Volont\xe9', ..."
403,7.9,Ying xiong,PG-13,Action,99,"[u'Jet Li', u'Tony Chiu Wai Leung', u'Maggie C..."
552,7.8,Kung Fu Hustle,R,Action,99,"[u'Stephen Chow', u'Wah Yuen', u'Qiu Yuen']"
740,7.6,The Raid: Redemption,R,Action,101,"[u'Iko Uwais', u'Ananda George', u'Ray Sahetapy']"
327,8.0,The Adventures of Robin Hood,PG,Action,102,"[u'Errol Flynn', u'Olivia de Havilland', u'Bas..."
515,7.8,Dirty Harry,R,Action,102,"[u'Clint Eastwood', u'Andrew Robinson', u'Harr..."
610,7.7,Enter the Dragon,R,Action,102,"[u'Bruce Lee', u'John Saxon', u'Jim Kelly']"
717,7.6,The Legend of Drunken Master,R,Action,102,"[u'Jackie Chan', u'Ho-Sung Pak', u'Lung Ti']"
729,7.6,The Crow,R,Action,102,"[u'Brandon Lee', u'Michael Wincott', u'Rochell..."
832,7.5,RoboCop,R,Action,102,"[u'Peter Weller', u'Nancy Allen', u""Dan O'Herl..."
675,7.7,Kiss Kiss Bang Bang,R,Action,103,"[u'Robert Downey Jr.', u'Val Kilmer', u'Michel..."
502,7.8,The French Connection,R,Action,104,"[u'Gene Hackman', u'Roy Scheider', u'Fernando ..."
653,7.7,Fearless,PG-13,Action,104,"[u'Jet Li', u'Li Sun', u'Yong Dong']"
954,7.4,X-Men,PG-13,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."

# Filtrando dataframes

In [14]:
boleanos = []

for length in filmes.duration:
    if length >= 200:
        boleanos.append(True)
    else:
        boleanos.append(False)

In [15]:
boleanos[:20]

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False]

In [21]:
len(boleanos)

979

In [16]:
duração = pd.Series(boleanos)
duração.head()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [17]:
#Podemos usar a notação de colchetes para indexar ou para aplicar filtros de series boleanas
print(filmes['title'][:10])

0                         The Shawshank Redemption
1                                    The Godfather
2                           The Godfather: Part II
3                                  The Dark Knight
4                                     Pulp Fiction
5                                     12 Angry Men
6                   The Good, the Bad and the Ugly
7    The Lord of the Rings: The Return of the King
8                                 Schindler's List
9                                       Fight Club
Name: title, dtype: object

In [18]:
filmes[duraçaõ]

NameError: name 'duraçaõ' is not defined

In [26]:
#pego a série boleana e aplico no no dataframe ele só trará os campos onde forem true, ou seja, campos maiores que 200
filmes[duração]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [19]:
filmes[duração][['title', 'star_rating']]

                                             title  star_rating
2                           The Godfather: Part II          9.1
7    The Lord of the Rings: The Return of the King          8.9
17                                   Seven Samurai          8.7
78                     Once Upon a Time in America          8.4
85                              Lawrence of Arabia          8.4
142              Lagaan: Once Upon a Time in India          8.3
157                             Gone with the Wind          8.2
204                                        Ben-Hur          8.1
445                           The Ten Commandments          7.9
476                                         Hamlet          7.8
630                                      Malcolm X          7.7
767                It's a Mad, Mad, Mad, Mad World          7.6

# podemos simplificar o filtro da forma abaixo ou com List Comprehension

In [21]:
#forma simplificada

A = filmes.duration >= 180
A.head(20)

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
Name: duration, dtype: bool

In [22]:
filmes[A]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
93,8.4,Dilwale Dulhania Le Jayenge,NOT RATED,Comedy,181,"[u'Shah Rukh Khan', u'Kajol', u'Amrish Puri']"
109,8.3,Dil Chahta Hai,NOT RATED,Comedy,183,"[u'Aamir Khan', u'Saif Ali Khan', u'Akshaye Kh..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
143,8.2,The Wolf of Wall Street,R,Biography,180,"[u'Leonardo DiCaprio', u'Jonah Hill', u'Margot..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
166,8.2,The Deer Hunter,R,Drama,182,"[u'Robert De Niro', u'Christopher Walken', u'J..."
184,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
220,8.1,Gandhi,PG,Biography,191,"[u'Ben Kingsley', u'John Gielgud', u'Candice B..."
245,8.1,Barry Lyndon,PG,Adventure,184,"[u""Ryan O'Neal"", u'Marisa Berenson', u'Patrick..."
316,8.0,JFK,R,Drama,189,"[u'Kevin Costner', u'Gary Oldman', u'Jack Lemm..."
318,8.0,Magnolia,R,Drama,188,"[u'Tom Cruise', u'Jason Robards', u'Julianne M..."
335,8.0,Doctor Zhivago,PG-13,Drama,197,"[u'Omar Sharif', u'Julie Christie', u'Geraldin..."
339,8.0,Dances with Wolves,PG-13,Adventure,181,"[u'Kevin Costner', u'Mary McDonnell', u'Graham..."
361,8.0,Fiddler on the Roof,G,Drama,181,"[u'Topol', u'Norma Crane', u'Leonard Frey']"
385,8.0,Spartacus,PG-13,Action,197,"[u'Kirk Douglas', u'Laurence Olivier', u'Jean ..."
424,7.9,The Right Stuff,R,Adventure,193,"[u'Sam Shepard', u'Scott Glenn', u'Ed Harris']"
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
611,7.7,Short Cuts,R,Comedy,187,"[u'Andie MacDowell', u'Julianne Moore', u'Tim ..."
620,7.7,Titanic,PG-13,Drama,194,"[u'Leonardo DiCaprio', u'Kate Winslet', u'Bill..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
671,7.7,Grindhouse,R,Action,191,"[u'Kurt Russell', u'Rose McGowan', u'Danny Tre..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [23]:
#Escrevendo por List Comprehension
filmes[filmes.duration >= 180].head()

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."

In [24]:
genero_maior_200 = filmes[filmes.duration >= 200].genre

In [25]:
genero_maior_200

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object

In [27]:
type(genero_maior_200)

pandas.core.series.Series

In [28]:
genero_maior_200 = filmes[filmes.duration >= 200]['genre']

In [29]:
genero_maior_200

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object

In [30]:
#Porém, por boa prática, utilizamos sempre o método LOC que nada mais é do que definir uam condição e filtrar por labels

filmes.loc[filmes.duration >= 200, 'genre']

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object